name: praxis_data
description: A new Flutter project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">2.15.1 <=3.3.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  clean_architecture:
    path: ../clean_architecture
  get_it: ^7.2.0
  injectable: ^1.5.3
  logger: ^1.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  firebase_analytics: ^9.3.3
  firebase_in_app_messaging: ^0.6.0+23
  google_sign_in: ^5.4.1
  praxis_flutter_domain:
    path: ../praxis_flutter_domain
  sqflite: ^2.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.1
  injectable_generator: any
  build_runner: any